version: '3'
services:
  react-app:
    container_name: react-crud-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge